#ifndef CNET_FRAME_DEFINITION_H
#define CNET_FRAME_DEFINITION_H

#define CNET_FRAME_STATUS_S 0x0000
#define CNET_FRAME_STATUS_UF 0x0001
#define CNET_FRAME_STATUS_CU 0x000A
#define CNET_FRAME_STATUS_REANA 0x000B
#define CNET_FRAME_STATUS_ADU 0x000C
#define CNET_FRAME_STATUS_AAD 0x000D
#define CNET_FRAME_STATUS_ASI 0x000E
#define CNET_FRAME_STATUS_CF 0x000F
#define CNET_FRAME_STATUS_AT 0x0010
#define CNET_FRAME_STATUS_AUHSA 0x0011
#define CNET_FRAME_STATUS_ADR 0x0012
#define CNET_FRAME_STATUS_ADSP 0x0013
#define CNET_FRAME_STATUS_ADP 0x0014
#define CNET_FRAME_STATUS_ADCA 0x0015
#define CNET_FRAME_STATUS_ADSM 0x0016
#define CNET_FRAME_STATUS_ADBPC 0x0017
#define CNET_FRAME_STATUS_ADBC 0x0018
#define CNET_FRAME_STATUS_ADSST 0x0019
#define CNET_FRAME_STATUS_ADDO 0x001A
#define CNET_FRAME_STATUS_II 0x0028
#define CNET_FRAME_STATUS_IGC 0x0029
#define CNET_FRAME_STATUS_IPC 0x002A
#define CNET_FRAME_STATUS_IA 0x002B
#define CNET_FRAME_STATUS_URV 0x002C
#define CNET_FRAME_STATUS_IRC 0x002D
#define CNET_FRAME_STATUS_CR 0x002E

#define CNET_FRAME_AUTH_OPEN 0x0000
#define CNET_FRAME_AUTH_WEP 0x0001
#define CNET_FRAME_AUTH_FT 0x0002
#define CNET_FRAME_AUTH_WPA3 0x0003

#define CNET_FRAME_REASON_UNSPECIFIED 0x0001
#define CNET_FRAME_REASON_ANLV 0x0002
#define CNET_FRAME_REASON_DL 0x0003
#define CNET_FRAME_REASON_DI 0x0004
#define CNET_FRAME_REASON_DAB 0x0005
#define CNET_FRAME_REASON_C2FN 0x0006
#define CNET_FRAME_REASON_C3FN 0x0007
#define CNET_FRAME_REASON_DSL 0x0008
#define CNET_FRAME_REASON_SNA 0x0009
#define CNET_FRAME_REASON_BPC 0x000A
#define CNET_FRAME_REASON_BSC 0x000B
#define CNET_FRAME_REASON_II 0x000D
#define CNET_FRAME_REASON_MF 0x000E
#define CNET_FRAME_REASON_4WHT 0x000F
#define CNET_FRAME_REASON_GKT 0x0010
#define CNET_FRAME_REASON_ID 0x0011
#define CNET_FRAME_REASON_IGC 0x0012
#define CNET_FRAME_REASON_IPC 0x0013
#define CNET_FRAME_REASON_IA 0x0014
#define CNET_FRAME_REASON_URV 0x0015
#define CNET_FRAME_REASON_IRC 0x0016
#define CNET_FRAME_REASON_8021XAF 0x0017
#define CNET_FRAME_REASON_CSR 0x0018

#define CNET_FRAME_ACTION_CSM 0x00
#define CNET_FRAME_ACTION_CQ 0x01
#define CNET_FRAME_ACTION_CD 0x02
#define CNET_FRAME_ACTION_CBA 0x03
#define CNET_FRAME_ACTION_CP 0x04
#define CNET_FRAME_ACTION_CRM 0x05
#define CNET_FRAME_ACTION_CFBT 0x06
#define CNET_FRAME_ACTION_CH 0x07
#define CNET_FRAME_ACTION_CSQ 0x08
#define CNET_FRAME_ACTION_CPD 0x09
#define CNET_FRAME_ACTION_CW 0x0A
#define CNET_FRAME_ACTION_CM 0x0D
#define CNET_FRAME_ACTION_CMH 0x0E
#define CNET_FRAME_ACTION_CSP 0x0F
#define CNET_FRAME_ACTION_CV 0x15
#define CNET_FRAME_ACTION_CVS 0x7F

#define CNET_FRAME_MACROS_ID cnet_hdr.id
#define CNET_FRAME_MACROS_ADDR1 cnet_hdr.addr1
#define CNET_FRAME_MACROS_ADDR2 cnet_hdr.addr2
#define CNET_FRAME_MACROS_ADDR3 cnet_hdr.addr3
#define CNET_FRAME_MACROS_SEQ cnet_hdr.seq
#define CNET_FRAME_MACROS_VERSION cnet_hdr.cnet_type.version
#define CNET_FRAME_MACROS_TYPE cnet_hdr.cnet_type.type
#define CNET_FRAME_MACROS_STYPE cnet_hdr.cnet_type.stype
#define CNET_FRAME_MACROS_FLAGS cnet_hdr.cnet_type.flags
#define CNET_FRAME_MACROS_RVERSION cnet_type.version
#define CNET_FRAME_MACROS_RTYPE cnet_type.type
#define CNET_FRAME_MACROS_RSTYPE cnet_type.stype
#define CNET_FRAME_MACROS_RFLAGS cnet_type.flags

#endif